import { readFileSync } from "node:fs"
import { resolve } from "node:path"
import { NextResponse } from "next/server"

/**
 * Serves llms.txt at https://aether-ui.dev/llms.txt
 *
 * The source file lives in apps/registry-public/public/llms.txt and is
 * regenerated by `pnpm --filter @aetherstack/scripts build-registry`.
 * This route reads the committed file at build time so the docs app is
 * the canonical host — no separate subdomain required.
 */
export const dynamic = "force-static"

export function GET() {
  const filePath = resolve(
    process.cwd(),
    "../../apps/registry-public/public/llms.txt",
  )

  const content = readFileSync(filePath, "utf-8")

  return new NextResponse(content, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, stale-while-revalidate=86400",
    },
  })
}
