import { defineConfig } from "tsup"

export default defineConfig({
  entry: [
    "src/index.ts",
    // Original 16
    "src/components/badge.tsx",
    "src/components/button.tsx",
    "src/components/card.tsx",
    "src/components/checkbox.tsx",
    "src/components/dialog.tsx",
    "src/components/input.tsx",
    "src/components/label.tsx",
    "src/components/radio-group.tsx",
    "src/components/select.tsx",
    "src/components/sheet.tsx",
    "src/components/skeleton.tsx",
    "src/components/switch.tsx",
    "src/components/table.tsx",
    "src/components/tabs.tsx",
    "src/components/textarea.tsx",
    "src/components/tooltip.tsx",
    // Phase 6 additions (15)
    "src/components/accordion.tsx",
    "src/components/avatar.tsx",
    "src/components/calendar.tsx",
    "src/components/combobox.tsx",
    "src/components/context-menu.tsx",
    "src/components/dropdown-menu.tsx",
    "src/components/hover-card.tsx",
    "src/components/pagination.tsx",
    "src/components/progress.tsx",
    "src/components/scroll-area.tsx",
    "src/components/separator.tsx",
    "src/components/slider.tsx",
    "src/components/toast.tsx",
    "src/components/toggle.tsx",
    "src/components/toggle-group.tsx",
    // Phase 7 additions (7)
    "src/components/alert.tsx",
    "src/components/alert-dialog.tsx",
    "src/components/collapsible.tsx",
    "src/components/drawer.tsx",
    "src/components/kbd.tsx",
    "src/components/popover.tsx",
    "src/components/spinner.tsx",
    // Phase 7.5 Track A additions (13)
    "src/components/aspect-ratio.tsx",
    "src/components/button-group.tsx",
    "src/components/carousel.tsx",
    "src/components/chart.tsx",
    "src/components/date-picker.tsx",
    "src/components/input-group.tsx",
    "src/components/input-otp.tsx",
    "src/components/menubar.tsx",
    "src/components/navigation-menu.tsx",
    "src/components/resizable.tsx",
    "src/components/sidebar.tsx",
    "src/components/sonner.tsx",
    "src/components/visually-hidden.tsx",
    // AI primitives barrel (14 components via ai/index.ts)
    "src/components/ai/index.ts",
  ],
  format: ["cjs", "esm"],
  dts: true,
  clean: true,
  sourcemap: true,
  treeshake: true,
  external: [
    "react",
    "react-dom",
    // Original Radix deps
    "@radix-ui/react-checkbox",
    "@radix-ui/react-dialog",
    "@radix-ui/react-label",
    "@radix-ui/react-radio-group",
    "@radix-ui/react-select",
    "@radix-ui/react-slot",
    "@radix-ui/react-switch",
    "@radix-ui/react-tabs",
    "@radix-ui/react-tooltip",
    // Phase 6 Radix deps
    "@radix-ui/react-accordion",
    "@radix-ui/react-avatar",
    "@radix-ui/react-context-menu",
    "@radix-ui/react-dropdown-menu",
    "@radix-ui/react-hover-card",
    "@radix-ui/react-popover",
    "@radix-ui/react-progress",
    "@radix-ui/react-scroll-area",
    "@radix-ui/react-separator",
    "@radix-ui/react-slider",
    "@radix-ui/react-toast",
    "@radix-ui/react-toggle",
    "@radix-ui/react-toggle-group",
    // Phase 7 Radix deps
    "@radix-ui/react-alert-dialog",
    "@radix-ui/react-collapsible",
    "vaul",
    // Phase 7.5 Radix deps
    "@radix-ui/react-aspect-ratio",
    "@radix-ui/react-menubar",
    "@radix-ui/react-navigation-menu",
    "@radix-ui/react-visually-hidden",
    // Phase 7.5 utility deps
    "embla-carousel-react",
    "input-otp",
    "react-resizable-panels",
    "sonner",
    "react-markdown",
    // Phase 6 utility deps
    "cmdk",
    "react-day-picker",
    "date-fns",
    "recharts",
    // Shared
    "class-variance-authority",
    "clsx",
    "lucide-react",
    "tailwind-merge",
    "@aetherstack/utils",
  ],
  esbuildOptions(options) {
    options.jsx = "automatic"
  },
})
